services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raybeststar_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
