services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raybeststar_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/raybeststar.com:/etc/letsencrypt/live/raybeststar.com:ro
      - /etc/letsencrypt/archive/raybeststar.com:/etc/letsencrypt/archive/raybeststar.com:ro
      - /etc/letsencrypt/renewal:/etc/letsencrypt/renewal:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    restart: always
